### ISSUE TITLE
Keys error with docker setup

### ISSUE THREAD

**Issue by heichwald** [madMAx43v3r/chia-gigahorse#203]
Hello,

I am running gigahorse-farmer fine but i would like to move to the docker setup.
I am running into this issue
```
herve-node-1   | CHIA_ROOT is set to /data/
herve-node-1   | Chia directory /data
herve-node-1   | SSL file permissions are correct
herve-node-1   | No keys are present in the keychain. Generate them with 'chia keys generate'
herve-node-1   | /data already exists, no migration action taken
herve-node-1   | Usage: chia.bin start [OPTIONS]
herve-node-1   |                       {all|data|data_layer_http|node|harvester|farmer|farmer-
herve-node-1   |                       no-wallet|farmer-only|timelord|timelord-only|timelord-
herve-node-1   |                       launcher-
herve-node-1   |                       only|wallet|introducer|simulator|crawler|seeder|seeder-
herve-node-1   |                       only}...
herve-node-1   | Try 'chia.bin start -h' for help.
herve-node-1   | 
herve-node-1   | Error: Invalid value for '{all|data|data_layer_http|node|harvester|farmer|farmer-no-wallet|farmer-only|timelord|timelord-only|timelord-launcher-only|wallet|introducer|simulator|crawler|seeder|seeder-only}...': '"farmer"' is not one of 'all', 'data', 'data_layer_http', 'node', 'harvester', 'farmer', 'farmer-no-wallet', 'farmer-only', 'timelord', 'timelord-only', 'timelord-launcher-only', 'wallet', 'introducer', 'simulator', 'crawler', 'seeder', 'seeder-only'.

```

I set it up in compose with
```
services:
  node:
    environment:
      - CHIA_SERVICES="farmer"
    image: chia-gigahorse-nvidia
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - /home/herve/.chia/mainnet:/data
```

Am I missing something? It seems i need `.chia/mainet` instead of just `.chia` but i still fails

Thanks
